### ISSUE TITLE
Fastjson1.2.5 <= 1.2.60时的第二个payload需要目标环境开启autotype

### ISSUE THREAD

**Issue by W01fh4cker** [safe6Sec/Fastjson#6]
`Fastjson1.2.5 <= 1.2.60`这里的这个payload，应该是需要目标环境开启`autotype`的，具体参考文章：https://blog.csdn.net/qq_36869808/article/details/123210898 ，我本地华夏`erp`的`2.3`版本（`Fastjson 1.2.55`）的环境，复现也显示`autoType is not support. org.apache.commons.configuration.JNDIConfiguration`。
![image](https://github.com/safe6Sec/Fastjson/assets/101872898/787beb39-397e-4fa6-82c4-41ca4c5fabd2)
![image](https://github.com/safe6Sec/Fastjson/assets/101872898/d41319b6-a91b-454f-ae39-c5efb606feeb)

**Comment by safe6Sec** [comment]
感谢反馈，已经修改
